#ifndef __PRUEBAS_COLA_H__
#define __PRUEBAS_COLA_H__


int DadaUnaColaVacia_CuandoSeQuiereEncolar_EntoncesEncolarDevolveraCero();
int DadaUnaCola_CuandoSeLaCrea_EntoncesLaPilaEstaVacia();
int DadaUnaColaVacia_CuandoSeQuiereDesencolar_EntoncesDesencolarDevolveraMenosUno();
int DadaUnaColaVacia_CuandoSeQuiereVerLaCantidad_EntoncesLaCantidadSeraCero();
int DadaUnaColaVacia_CuandoSeQuiereVerElPrimerElemento_EntoncesDevolveraNull();

int DadaUnaColaNull_CuandoSeQuiereEncolar_EntoncesDevolveraNull();
int DadaUnaColaNull_CuandoSeQuiereDecencolar_EntoncesDevolveraNull();
int DadaUnaColaNull_CuandoSeQuiereVerSiLaColaEstaVacia_EntoncesDevolveraTrue();
int DadaUnaColaNull_CuandoSeQuiereVerLaCantidadDeElementos_EntoncesDevolveraCero();
int DadaUnaColaNull_CuandoSeQuiereVerElPrimerElemento_EntoncesDevolveraNull();
int DadaUnaColaNull_CuandoSeEncolaUnElementoNull_EntoncesDevolveraMenosUno();
int DadaUnaColaDistintaDeNull_CuandoSeEncolaUnElementoNull_EntoncesDevolveraCero();
int DadaUnaColaDistintaDeNull_CuandoSeDesencolaUnElementoNull_EntoncesDevolveraCero();

int DadaUnaColaInicializada_CuandoSeEncolanYDesencoLaMismaCantidadDeElementos_EntoncesLaColaQuedaraVacia();
int DadaUnaColaInicializa_CuandoSeEncolanElementos_EntoncesLaCantidadDeElementosEncoladaEsLaCorrecta();
int DadaUnaColaInicializada_cuandoSeEncolaUnElemento_EntoncesElPrimerElementoSeraEse();
int DadaUnaColaInicializada_CuandoSeEncolanMasElementosDeLosQueSeDesencolan_EntoncesLaColaNoEstaVacia();
int DadaUnaColaInicializada_CuandoSeEncolanYDesencolanElementos_EntoncesDevolveraElElementoCorrecto();
int DadaUnaColaInicializada_CuandoSeDesencolanElementos_EntoncesDeveraImprimirloCorrectamente();

int DadaUnaColaInicializada_CuandoEncoloMuchosElementos_EntoncesLaCantidadSeraLaCorrecta();
int DadaUnaColaIniciliazada_CuandoEncoloYDesencoloMuchosElementos_EntoncesLaColaQuedaVacia();
int DadaUnaColaInicializada_CuandoSeEncolaronYSesencolaronMuchosElementos_EntoncesLaColaNoEstaVacia();
int DadaUnaColaInicializada_CuandoSeEncolanYDesencolanMuchosElementos_EntonceseElElementoPrimeroEsElCorrecto();

#endif /* __PRUEBAS_COLA_H__ */
