#ifndef __PRUEBA_H__
#define __PRUEBA_H__


int dadaunapilavacia_cuandosequieredesapilar_entoncesdevolveramenosuno();
int dadaunapilavacia_cuandosequiereverelelementodeltope_entonesdevolveranull();
int dadaunapilanull_cuandosequiereapilar_entoncesdevolveramenosuno();
int dadaunapilanull_cuandosequieredesapilar_entoncesdevolveramenosuno();
int dadaunapilayainicializada_cuandosequiereapilarydesapilarlamismacantidaddeelelementos_entonceslapilaquedaravacia();
int dadaunapila_cuandoseapilaunnumerograndedeelementos_entoncesveoqueapiletodos();
int dadaunapila_cuandosequiereverqueredimencione_entoncesseagrandaraoachicaraelvector();
int dadaunapilaconelementos_cuandosequiereverquedesapilecorrectamente_entoncesimprimiraloselementosalrevez();
int dadaunapilainicializada_cuandoapilomaselementosdelosquedesapilo_entonceslacantidaddeelementosesmayorquecero();
int dadaunapilanull_cuandosequieresabersiestavacia_entoncesdaratrue();
int dadaunapilainicializada_cuandosequiereagregarunelemento_entonceseltopeeselelementoapilado();
int dadaunapila_cuandoselaquierecrear_entoncesdeberacumplirconlascondicionesiniciales();
int dadaunapilainicializada_cuandosequiereapilarydesapilarelementosnull_entoncesdevolveraexito();
int dadaunapilainicializada_cuandosedeseadesapilar3elementos_entoncesdevolveraeltopeadecuado();
int dadaunapilanull_cuandonosequiereverlacantidaddeelmentos_entoncesdevolveracero();
int dadaunapilainicializada_cuandoapilanelementos_entonceseltopedeveserdistintodenull();
int dadaunapilainicializada_cuandosedesapilaelultimoelemento_entoncespilatopedevuleveelelemetocorrespondiente();
int dadaunapilainilizalizada_cuandoseapilanmaselementosdelosquesedesapilan_entonceslapilanoestaravacia();


#endif /* __PRUEBA_H__ */
